version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Frontend/frontend-new/Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

  backend:
    image: backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    depends_on:
      - sql.data
      - identityserver
    ports:
      - "8182:8182"

  identityserver:
    image: identityserver
    build:
      context: .
      dockerfile: Identity/IdentityServerExample-IdentityServer.WebApplication.Testing.Features/Dockerfile
    ports:
      - "7199:7199"
    depends_on:
      - sql.data

  sql.data:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ConnectionString=Server=host.docker.internal;Initial Catalog=TrainingHelperAlevel;Integrated Security=True;MultipleActiveResultSets=true;UserId=DESKTOP-7HK7ORN\Кирилл;
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"